###
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1898442413",
  "amount": 100
}

###거래 취소
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId":"a731549df98543f6bca87ffd81dc6861",
  "accountNumber": "1898442413",
  "amount": 100
}